### ISSUE TITLE
EPIC: H support (All existing features, new protocol features not tracked in this issue)

### ISSUE THREAD

**Issue by Innkst** [ecadlabs/taquito#1028]
<details>
	<summary>Integration with the final Hprotocol</summary>

## Tasks to make sure existing projects using v10 continue to work with v11/h...net

- [ ] Setup `h..net` public nodes (https://api.tez.ie/rpc/florencenet)
- [ ] Add `h..net` to the keygen API
- [ ] Add `h..net` to integration tests
- [ ] Add `h..net` constants ` packages/taquito/src/constants.ts`
- [ ] Deploy lambda-view contract
- [ ] Add new protocol to the `ContractView` class for [lambdaView](https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/contract.ts#L134)
- [ ] Deploy `knownContract` for tests
- [ ] Delploy `knownBigMapContract`
- [ ] Update known baker address `tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD`
- [ ] Update estimate values form `h..net` 
- [ ] Add the protocol to the michel-codec package
- [ ] Add the protocol to the tzip16 package, in the michelson-storage-view.ts
- [ ] Add GitHub Actions to run grandanet tests from CI
</details>

## Assess the impact of New Features/Functionality in H and create follow-up issues to add support for them:
- Global Constants
- Michelson On-Chain Views: 
   - There are two added Michelson primitives: VIEW (instruction) and view (top-level keyword).
- Timelock: Added timelock-related types and opcodes to Michelson
- RPC changes:
   - Deprecated RPC POST ../endorsing_power has been removed. Clients already used GET ../helpers/endorsing_rights which is clearer, as powerful and equally costly in terms of computation for the node. 
   - The RPCs GET ../context/delegates/[PUBLIC_KEY_HASH]/.. now fail gracefully with a specific error delegate.not_registered when PUBLIC_KEY_HASH is not a delegate instead of the generic context.storage_error. 
   - New RPCs for cache:
      - The new RPC context/cache/contracts/all returns the list of contracts in the cache.
      - The new RPC context/cache/contracts/size returns an overapproximation of the cache size (in bytes).
      - The new RPC context/cache/contracts/size_limit returns the maximal cache size (in bytes). When this size is reached, the cache removes the least recently used entries.
      - The new RPC context/cache/contract_rank gives the number of contracts that are less recently used than the one provided as argument.
      - The new RPC scripts/script_size gives the size of the script and its storage when stored in the cache.
   - RPCs GET ../helpers/endorsing_rights and GET ../helpers/baking_rewards have been moved into the RPC plugin
- Minor changes:
   - The size limit on Michelson types has been roughly doubled (from 1000 to 2001)
   - Multiple gas reduction improvement may have impact on operation estimations.
## Resources
- H: https://tezos.gitlab.io/protocols/011_hangzhou.html

## Misc notes

To get the list of protocol hash's supported `tezos-admin-client list protocols`
`PsrsRVg1Gycjn5LvMtoYSQah1znvYmGp8bHLxwYLBZaYFf2CEkV`    proto hash for `falphanet`, short version `PsrsRVg1`
