### ISSUE TITLE
delphinet support

### ISSUE THREAD

**Issue by jevonearth** [ecadlabs/taquito#426]
- [x] Setup public `delphinet` nodes
- [x] Add `delphinet` to CI jobs (ignore failures)
- [x] Run all tests (fuacet key) @roxaneletourneau 
- [x] Remove the MINIMAL_FEE_PER_STORAGE_BYTE_MUTEZ constant in Taquito: take the value from the RPC API (cost_per_byte) which is different in Delphinet and Carthagenet
- [x]  Add support for the new parameters in operation result which give the gas in milligas in Delphinet (consumed_milligas)
- [x]  Figure out how emptying an account is affected by the changes
- [x] Provision `delphinet` support for keys API
- [x] Delphinet CI job is temporally using a faucet and only node 10. Change for ephemeral key and add node 12 when `Provision delphinet support for keys API` task is ready.
- [x] Triage & evaluate any proposed breaking changes we want to ship in this major number update
- [x] Update CI to halt on `delphinet` CI failures
- [x] Remove `Tezos.importKey()` as per #315 
- [x] Remove default node URL as per #388
- [x] Publish upgrade guide (https://tezostaquito.io/docs/v7_breaking_changes)
- [x] Make v7 RC1
- [ ] Update all demo apps to pre-release version
  - [x] TacoWallet
  - [x] key-gen-api
  - [x] taquito demo
  - [ ] ligo web-ide @roxaneletourneau 
  - [x] token faucet (@claudebarde )
  - [x] George Clony @sean-magin 
  - [x] Taquito Website
  - [ ] Taquito template projects
    - [x] https://github.com/ecadlabs/taquito-boilerplate @claudebarde 
    - [ ] https://github.com/ecadlabs/taquito-react-template @claudebarde 
- [x] Write Final release notes @jevonearth 
- [x] Blog post @jevonearth 
- [x] Hit the pavements, let all known teams know of the upcoming release
  - [x] MadFish / Thanos / quipuswap
  - [x] Truffle trufflesuite/truffle#3500
  - [x] ZenGo
  - [x] Dexter
  - [x] Kukai
  - [x] Tezos Domains
  - [x] TQTezos
  - [x] AirGap / TZButton
  - [x] Stove Labs
  - [x] Better Call Dev https://github.com/baking-bad/bcd
- [x] Publish release
- [x] Update website changlogs and version number on website.
- [x] Outreach to existing users to upgrade prior to new protocol transition. (Hopefully, no dep left behind)
- [x] Update this SE question: https://tezos.stackexchange.com/questions/2234/taquito-default-entrypoint-not-found @roxaneletourneau 
- [x] Run the ledger signer integration tests on Delphinet

Resources:

* https://blog.nomadic-labs.com/delphi-changelog.html

**Comment by jevonearth** [comment]
New delphinet nodes are up. Next step is to expose them via `api.tez.ie/rpc/delphinet`

**Comment by jevonearth** [comment]
The first release candidate was pushed yesterday. It is available on npmjs:

use `npm i @taquito/taquito@7.0.0-beta-RC.0`

**Comment by jevonearth** [comment]
@claudebarde can you confirm token-faucet is done, and can you also update the react-template project and "george cloney" please?

**Comment by jevonearth** [comment]
Thank you @roxaneletourneau for your amazing work on this release!
