### ISSUE TITLE
Florence support (All existing features, new protocol features not tracked in this issue)

### ISSUE THREAD

**Issue by kjaiswal** [ecadlabs/taquito#631]
<details>
	<summary>Integration with the florence**noba**net protocol</summary>
## Tasks to make sure existing projects using v8 continue to work with v9/florencenet

- [x] Setup `florencenet` public nodes (https://api.tez.ie/rpc/florencenet)
- [x] Add `florencenet` to the keygen API
- [x] Add `florencenet` to integration tests
- [x] Add `florencenet` constants ` packages/taquito/src/constants.ts`
- [x] Deploy lambda-view contract
- [x] Add new protocol to the `ContractView` class for [lambdaView](https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/contract.ts#L134)
- [x] Deploy `knownContract` for tests
- [x] Delploy `knownBigMapContract`
- [x] Update known baker address `tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD`
- [x] Update estimate values form `florencenet` 
- [x] Add the protocol to the michel-codec package
- [x] Add the protocol to the tzip16 package, in the michelson-storage-view.ts
- [x] Add GitHub Actions to run florencenet tests from CI

</details>
<details>
	<summary>Integration with the falphanet protocol</summary>
## Tasks to make sure existing projects using v8 continue to work with v9/falphanet

- [x] Setup `falphanet` public nodes (https://api.tez.ie/rpc/falphanet)
- [x] Add `falphanet` to the keygen API
- [x] Add `falphanet` to integration tests
- [x] Add `falphanet` constants ` packages/taquito/src/constants.ts`
- [x] Deploy lambda-view contract
- [x] Add new protocol to the `ContractView` class for [lambdaView](https://github.com/ecadlabs/taquito/blob/master/packages/taquito/src/contract/contract.ts#L134)
- [x] Deploy `knownContract` for tests
- [x] Delploy `knownBigMapContract`
- [x] Update known baker address `tz1cjyja1TU6fiyiFav3mFAdnDsCReJ12hPD`
- [ ] Update estimate values form `falphanet` 
- [x] Add the protocol to the michel-codec package
- [x] Add the protocol to the tzip16 package, in the michelson-storage-view.ts
- [x] Add GitHub Actions to run falphanet tests from CI

</details>
<details>
	<summary>Integration with the falphanet protocol</summary>
	fbetanet nor florencenet are released yet!
</details>

## New Features/Functionality - OUT OF SCOPE:
- [x] META TASK - Extract list of features and changes in 009 Change Log and list here. Impact assesment required.
See https://www.notion.so/ecad/Florence-features-2e3f790caee24b65ac25e2bcce7b57b5#c016905a2ee243c9997088d73459e9e7 for more details.

## Release tasks

TBD

## Resources

- 009 Florence Protocol Change Log https://gitlab.com/tezos/tezos/-/blob/11b12c4a677228c75c25d8b668d03704b083bed5/docs/protocols/009_florence.rst _Warning, specific hash, check you are looking at the latest revision!_
- ~Baking Accounts~ This will not be in effect with Florence anymore.
  - [TZIP Draft Baking accounts](https://gitlab.com/tzip/tzip/-/merge_requests/133)
  - [MR Baking accounts](https://gitlab.com/tezos/tezos/-/merge_requests/2458)
  - [MR Baking accounts Documentation](https://gitlab.com/tezos/tezos/-/merge_requests/2490)

## Misc notes

To get the list of protocol hash's supported `tezos-admin-client list protocols`
`PsrsRVg1Gycjn5LvMtoYSQah1znvYmGp8bHLxwYLBZaYFf2CEkV`    proto hash for `falphanet`, short version `PsrsRVg1`

Code diff for similar work [here](https://github.com/ecadlabs/taquito/commit/14dad3b55955e7a3b1cfee5a89c425097315386e).

take this opportunity to add more steps and refine our [wiki](https://www.notion.so/ecad/Adding-a-new-protocol-07496f004819476599a08b76e8464c14). We want to :

**Comment by kjaiswal** [comment]
npm run test:falphanet-faucet

Test Suites: 12 failed, 2 skipped, 32 passed, 44 of 46 total
Tests:       18 failed, 68 skipped, 211 passed, 297 total

PASS  ./contract-no-annotations-call-by-index.spec.ts (107.069 s)
PASS  ./contract-originate-token-contract.spec.ts (51.686 s)
PASS  ./contract-tx-wait-2-confirmations.spec.ts (67.092 s)
PASS  ./contract-manager-that-calls-failwith-contract.spec.ts (59.543 s)
PASS  ./tzip16-originate-contracts-with-metadata-on-HTTPS-and-fetch-metadata.spec.ts (121.836 s)
PASS  ./contract-with-bigmap-init.spec.ts (31.89 s)
PASS  ./contract-empty-unrevealed-implicit-account.spec.ts (76.62 s)
PASS  ./contract-pair-as-key.spec.ts (68.723 s)
PASS  ./multisig-contract-scenario.spec.ts (78.132 s)
PASS  ./contract-simple-origination.spec.ts (39.721 s)
PASS  ./contract-collections.spec.ts (115.104 s)
PASS  ./contract-michelson-origination.spec.ts (30.782 s)
PASS  ./contract-big-map.spec.ts (29.372 s)
PASS  ./tzip12-token-metadata.spec.ts (72.178 s)
PASS  ./tzip16-originate-contracts-with-metadata-on-HTTPS-and-sha256-hash-and-fetch-metadata.spec.ts (74.749 s)
PASS  ./tzip16-non-compliant-contract.spec.ts (31.261 s)
PASS  ./contract-originate-contract-with-bool.spec.ts (71.202 s)
PASS  ./contract-with-bad-code.spec.ts
PASS  ./contract-origination-wrong-order-code-porps.spec.ts (44.205 s)
PASS  ./contract-failwith.spec.ts (33.125 s)
PASS  ./contract-ligo-increment-contract.spec.ts (64.797 s)
PASS  ./contract-init-with-empty-bigmap.spec.ts (27.993 s)
PASS  ./contract-empty-delegated-implicit-account.spec.ts (70.594 s)
PASS  ./contract-empty-revealed-implicit-account.spec.ts (91.327 s)
PASS  ./tzip16-originate-contracts-with-metadata-on-itself-and-fetch-metadata.spec.ts (65.028 s)
PASS  ./contract-estimation-tests.spec.ts (31.437 s)
PASS  ./taquito-rpc.spec.ts
PASS  ./contract-unit-as-param.spec.ts (55.514 s)
PASS  ./wallet-api.spec.ts (140.055 s)
PASS  ./contract-call-with-xtz-amount.spec.ts (82.183 s)
PASS  ./tzip16-originate-contract-having-metadata-on-IPFS-and-fetch-those.spec.ts (52.888 s)
PASS  ./contract-big-map-access-by-index.spec.ts (44.322 s)

FAIL  ./contract-set-delegate-auto-estimate.spec.ts (6.264 s)
● Test account delegation with estimation using: https://api.tez.ie/rpc/falphanet › delegates account to known baker with automatic estimate
FAIL  ./local-forging.spec.ts (53.668 s)
● Test local forger: https://api.tez.ie/rpc/falphanet › Should give the same result as when forging with the rpc: Transaction with custom entrypoint (https://api.tez.ie/rpc/falphanet)
FAIL  ./lambda-view.spec.ts (130.939 s)
● Lambda view using: https://api.tez.ie/rpc/falphanet › Originate FA1.2 contract and fetch data from view entrypoints
● Lambda view using: https://api.tez.ie/rpc/falphanet › Originate a contract and fetch data from view entrypoints
● Lambda view using: https://api.tez.ie/rpc/falphanet › Originate FA2 contract and fetch data from view entrypoints
FAIL  ./tzip16-originate-fa2-contract-with-metadata-on-HTTPS-and-fetch-metadata.spec.ts (63.56 s)
● Tzip16 metadata and view on a fa2 contract: https://api.tez.ie/rpc/falphanet › Should execute views
FAIL  ./contract-simple-delegation.spec.ts
● test2 › https://api.tez.ie/rpc/falphanetsucceeds in delegating its account to a known baker
FAIL  ./contract-originate-vote-contract.spec.ts (5.032 s)
● Originate a voting contract using: https://api.tez.ie/rpc/falphanet › originates a voting contract and inits the storage
FAIL  ./contract-originate-contract-unpair.spec.ts (110.508 s)
● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code and init in Michelson
● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in Michelson and init in JSON Michelson
● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in Michelson and storage
● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in JSON Michelson and init in Michelson
FAIL  ./manager-contract-scenario.spec.ts
● Manager TZ: https://api.tez.ie/rpc/falphanet › test manager transfers scenarios for Babylon/005
FAIL  ./wallet-originate-contract-unpair.spec.ts (154.173 s)
● Test origination of a token contract using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in JSON Michelson and storage
FAIL  ./tzip16-metadata-view.spec.ts (92.307 s)
● Execute views example from TZComet: https://api.tez.ie/rpc/falphanet › Deploy a contract with metadata having views that return bytes (example taken from TZComet) and call the views
● Execute views example from TZComet: https://api.tez.ie/rpc/falphanet › Deploy a contract with metadata having a couple of views (example taken from TZComet) and call the views
FAIL  ./batch-api.spec.ts (214.111 s)
● Test batch api using: https://api.tez.ie/rpc/falphanet › Chain contract calls
FAIL  ./contract-originate-invalid-string.spec.ts (5.824 s)
● Test invalid data for origination using: https://api.tez.ie/rpc/falphanet › fails because non-ascii in init data

**Comment by kjaiswal** [comment]
Summary of all failing tests
 FAIL  ./contract-originate-invalid-string.spec.ts (5.824 s)
  ● Test invalid data for origination using: https://api.tez.ie/rpc/falphanet › fails because non-ascii in init data

    expect(received).toEqual(expected) // deep equality

    Expected: ObjectContaining {"message": StringContaining "invalid_constant"}
    Received: {"errors": [{"expected_type": {"prim": "string"}, "id": "proto.009-PsrsRVg1.michelson_v1.ill_typed_data", "ill_typed_expression": {"string": "Copyright Â©"}, "kind": "permanent"}, {"expected_type": {"prim": "string"}, "id": "proto.009-PsrsRVg1.michelson_v1.invalid_constant", "kind": "permanent", "location": 0, "wrong_expression": {"string": "Copyright Â©"}}, {"expected_form": "a printable ascii string", "id": "proto.009-PsrsRVg1.michelson_v1.invalid_syntactic_constant", "kind": "permanent", "location": 0, "wrong_expression": {"string": "Copyright Â©"}}], "id": "proto.009-PsrsRVg1.michelson_v1.invalid_syntactic_constant", "kind": "permanent", "message": "(permanent) proto.009-PsrsRVg1.michelson_v1.invalid_syntactic_constant", "name": "TezosOperationError"}

      30 |           expect(ex).toEqual(expect.objectContaining({ message: expect.stringContaining('invalidSyntacticConstantError') }))
      31 |         } else {
    > 32 |           expect(ex).toEqual(expect.objectContaining({ message: expect.stringContaining('invalid_constant') }))
         |                      ^
      33 |         }
      34 |       }
      35 |       done();

      at contract-originate-invalid-string.spec.ts:32:22
      at step (contract-originate-invalid-string.spec.ts:33:23)
      at Object.throw (contract-originate-invalid-string.spec.ts:14:53)
      at rejected (contract-originate-invalid-string.spec.ts:6:65)

 FAIL  ./batch-api.spec.ts (214.111 s)
  ● Test batch api using: https://api.tez.ie/rpc/falphanet › Chain contract calls

    TezosOperationError: (permanent) proto.009-PsrsRVg1.michelson_v1.deprecated_instruction

       96 |     })
       97 |
    >  98 |     it('Chain contract calls', async (done) => {
          |     ^
       99 |       const op = await Tezos.contract.originate({
      100 |         balance: "1",
      101 |         code: managerCode,

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (batch-api.spec.ts:98:5)

 FAIL  ./tzip16-metadata-view.spec.ts (92.307 s)
  ● Execute views example from TZComet: https://api.tez.ie/rpc/falphanet › Deploy a contract with metadata having views that return bytes (example taken from TZComet) and call the views

    HttpResponse: Http error response: (400) Failed to parse the request body: Missing object field balance

      14 | 		});
      15 |
    > 16 | 		it('Deploy a contract with metadata having views that return bytes (example taken from TZComet) and call the views', async (done) => {
         | 		^
      17 | 			// KT1S5Q7iN9ybuBuJviDYzXf7Mq94ToETwBJS
      18 |
      19 | 			const metadataBigMAp = new MichelsonMap();

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tzip16-metadata-view.spec.ts:16:3)

  ● Execute views example from TZComet: https://api.tez.ie/rpc/falphanet › Deploy a contract with metadata having a couple of views (example taken from TZComet) and call the views

    HttpResponse: Http error response: (400) Failed to parse the request body: Missing object field balance

      60 | 		});
      61 |
    > 62 | 		it('Deploy a contract with metadata having a couple of views (example taken from TZComet) and call the views', async (done) => {
         | 		^
      63 | 			// KT18tKt6ysL5QVqLMmwQL5p5Nu6m8KjRbhSb
      64 | 			const metadataBigMAp = new MichelsonMap();
      65 | 			metadataBigMAp.set("", char2Bytes('tezos-storage:here'));

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tzip16-metadata-view.spec.ts:62:3)

 FAIL  ./wallet-originate-contract-unpair.spec.ts (154.173 s)
  ● Test origination of a token contract using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in JSON Michelson and storage

    HttpRequestFailed: Request to https://api.tez.ie/rpc/falphanet/chains/main/blocks/head/header failed

      130 |         });
      131 |
    > 132 |         test('Originates a contract having UNPAIR with code in JSON Michelson and storage', async (done) => {
          |         ^
      133 |             const op = await Tezos.wallet.originate({
      134 |                 code: miObject,
      135 |                 storage: {

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (wallet-originate-contract-unpair.spec.ts:132:9)

 FAIL  ./manager-contract-scenario.spec.ts
  ● Manager TZ: https://api.tez.ie/rpc/falphanet › test manager transfers scenarios for Babylon/005

    HttpRequestFailed: Request to https://api.tez.ie/rpc/falphanet/chains/main/blocks/head/header failed

      11 |       done()
      12 |     })
    > 13 |     it('test manager transfers scenarios for Babylon/005', async (done) => {
         |     ^
      14 |       const op = await Tezos.contract.originate({
      15 |         balance: "1",
      16 |         code: managerCode,

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (manager-contract-scenario.spec.ts:13:5)

 FAIL  ./contract-originate-contract-unpair.spec.ts (110.508 s)
  ● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code and init in Michelson

    HttpResponse: Http error response: (500) [{"kind":"temporary","id":"failure","msg":"Error while applying operation opK4NdvoDYXFhcedtAero1FDfa3MkYfBfYDmWdyVqa3vrNFXTe6:\nbranch refused (Error:\n                  Counter 936 already used for contract tz1dNLAaEYAyQyoi6v5WG9qgC3Ck7Z6bL7QA (expected 937)\n)"}]

      12 |         });
      13 |
    > 14 |         test('Originates a contract having UNPAIR with code and init in Michelson', async (done) => {
         |         ^
      15 |             const op = await Tezos.contract.originate({
      16 |                 code: miStr,
      17 |                 init: '(Pair 0 "tz1QZ6KY7d3BuZDT1d19dUxoQrtFPN2QJ3hn")'

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (contract-originate-contract-unpair.spec.ts:14:9)

  ● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in Michelson and init in JSON Michelson

    HttpResponse: Http error response: (500) [{"kind":"temporary","id":"failure","msg":"Error while applying operation opK4NdvoDYXFhcedtAero1FDfa3MkYfBfYDmWdyVqa3vrNFXTe6:\nbranch refused (Error:\n                  Counter 936 already used for contract tz1dNLAaEYAyQyoi6v5WG9qgC3Ck7Z6bL7QA (expected 937)\n)"}]

      36 |         });
      37 |
    > 38 |         test('Originates a contract having UNPAIR with code in Michelson and init in JSON Michelson', async (done) => {
         |         ^
      39 |             const op = await Tezos.contract.originate({
      40 |                 code: miStr,
      41 |                 init: { prim: 'Pair', args: [{ int: '0' }, { string: 'tz1QZ6KY7d3BuZDT1d19dUxoQrtFPN2QJ3hn' }] }

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (contract-originate-contract-unpair.spec.ts:38:9)

  ● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in Michelson and storage

    HttpResponse: Http error response: (500) [{"kind":"temporary","id":"failure","msg":"Error while applying operation opK4NdvoDYXFhcedtAero1FDfa3MkYfBfYDmWdyVqa3vrNFXTe6:\nbranch refused (Error:\n                  Counter 936 already used for contract tz1dNLAaEYAyQyoi6v5WG9qgC3Ck7Z6bL7QA (expected 937)\n)"}]

      60 |         });
      61 |
    > 62 |         test('Originates a contract having UNPAIR with code in Michelson and storage', async (done) => {
         |         ^
      63 |             const op = await Tezos.contract.originate({
      64 |                 code: miStr,
      65 |                 storage: {

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (contract-originate-contract-unpair.spec.ts:62:9)

  ● Test origination of contract with UNPAIR using: https://api.tez.ie/rpc/falphanet › Originates a contract having UNPAIR with code in JSON Michelson and init in Michelson

    HttpResponse: Http error response: (500) [{"kind":"temporary","id":"failure","msg":"Error while applying operation ooeM85Lk97skcgzJT9U6T5zCH4pdgVF9Y22AzoHcVxPUmcsQmcP:\nbranch refused (Error:\n                  Counter 937 already used for contract tz1dNLAaEYAyQyoi6v5WG9qgC3Ck7Z6bL7QA (expected 938)\n)"}]

      87 |         });
      88 |
    > 89 |         test('Originates a contract having UNPAIR with code in JSON Michelson and init in Michelson', async (done) => {
         |         ^
      90 |             const op = await Tezos.contract.originate({
      91 |                 code: miObject,
      92 |                 init: '(Pair 0 "tz1QZ6KY7d3BuZDT1d19dUxoQrtFPN2QJ3hn")'

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (contract-originate-contract-unpair.spec.ts:89:9)

 FAIL  ./contract-originate-vote-contract.spec.ts (5.032 s)
  ● Originate a voting contract using: https://api.tez.ie/rpc/falphanet › originates a voting contract and inits the storage

    TezosOperationError: (permanent) proto.009-PsrsRVg1.michelson_v1.deprecated_instruction

      10 |       done()
      11 |     })
    > 12 |     it('originates a voting contract and inits the storage', async (done) => {
         |     ^
      13 |       // TODO: probably remove this as very expensive
      14 |       const op = await Tezos.contract.originate({
      15 |         balance: "1",

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (contract-originate-vote-contract.spec.ts:12:5)

 FAIL  ./contract-simple-delegation.spec.ts
  ● test2 › https://api.tez.ie/rpc/falphanetsucceeds in delegating its account to a known baker

    expect(received).toMatch(expected)

    Expected substring: "delegate.unchanged"
    Received string:    "Http error response: (400) Failed to parse the request body: No case matched:
      At /kind, unexpected string instead of endorsement
      At /kind, unexpected string instead of seed_nonce_revelation
      At /kind, unexpected string instead of endorsement_with_slot
      At /kind, unexpected string instead of double_endorsement_evidence
      At /kind, unexpected string instead of double_baking_evidence
      At /kind, unexpected string instead of activate_account
      At /kind, unexpected string instead of proposals
      At /kind, unexpected string instead of ballot
      At /kind, unexpected string instead of reveal
      At /kind, unexpected string instead of transaction
      At /kind, unexpected string instead of origination
      At /kind, unexpected string instead of origination
      At /delegate:
        Unhandled error (Failure \"Unexpected data (Signature.Public_key_hash)\")
      Missing object field version
      At /kind, unexpected string instead of failing_noop
      At /kind, unexpected string instead of baker_registration"

      30 |       } catch (ex) {
      31 |         //When running tests more than one time with the same faucet key, the account is already delegated to the given delegate
    > 32 |         expect(ex.message).toMatch('delegate.unchanged')
         |                            ^
      33 |       }
      34 |       done();
      35 |     });

      at contract-simple-delegation.spec.ts:32:28
      at step (contract-simple-delegation.spec.ts:33:23)
      at Object.throw (contract-simple-delegation.spec.ts:14:53)
      at rejected (contract-simple-delegation.spec.ts:6:65)

 FAIL  ./tzip16-originate-fa2-contract-with-metadata-on-HTTPS-and-fetch-metadata.spec.ts (63.56 s)
  ● Tzip16 metadata and view on a fa2 contract: https://api.tez.ie/rpc/falphanet › Should execute views

    HttpResponse: Http error response: (400) Failed to parse the request body: Missing object field balance

      413 |       });
      414 |
    > 415 |       it('Should execute views', async (done) => {
          |       ^
      416 |          // delphinet: KT1DNapRVdG9t74fzAvXLcKDcgxZd1i1TobV
      417 |          // edonet: KT1XKs56Z8iXpYAD3pzfyXC3B4maJciob74X
      418 |

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (tzip16-originate-fa2-contract-with-metadata-on-HTTPS-and-fetch-metadata.spec.ts:415:7)

 FAIL  ./lambda-view.spec.ts (130.939 s)
  ● Lambda view using: https://api.tez.ie/rpc/falphanet › Originate FA1.2 contract and fetch data from view entrypoints

    Undefined LambdaContract error: This might happen if you are using a sandbox. Please provide the address of a lambda contract as a parameter of the read method.

      15 |     });
      16 |
    > 17 |     it('Originate FA1.2 contract and fetch data from view entrypoints', async done => {
         |     ^
      18 |       const mapAccount1 = new MichelsonMap();
      19 |       mapAccount1.set('tz1h3rQ8wBxFd8L9B3d7Jhaawu6Z568XU3xY', '25');
      20 |       mapAccount1.set('tz1Nu949TjA4zzJ1iobz76fHPZbWUraRVrCE', '25');

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (lambda-view.spec.ts:17:5)

  ● Lambda view using: https://api.tez.ie/rpc/falphanet › Originate a contract and fetch data from view entrypoints

    Undefined LambdaContract error: This might happen if you are using a sandbox. Please provide the address of a lambda contract as a parameter of the read method.

      61 |
      62 |
    > 63 |     it('Originate a contract and fetch data from view entrypoints', async done => {
         |     ^
      64 |
      65 |       const mapAccount2 = new MichelsonMap();
      66 |       mapAccount2.set('tz1gvF4cD2dDtqitL3ZTraggSR1Mju2BKFEM', '25');

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (lambda-view.spec.ts:63:5)

  ● Lambda view using: https://api.tez.ie/rpc/falphanet › Originate FA2 contract and fetch data from view entrypoints

    Undefined LambdaContract error: This might happen if you are using a sandbox. Please provide the address of a lambda contract as a parameter of the read method.

      105 |
      106 |
    > 107 |     it('Originate FA2 contract and fetch data from view entrypoints', async done => {
          |     ^
      108 |
      109 |       const bigMapLedger = new MichelsonMap();
      110 |       bigMapLedger.set('tz1c1X8vD4pKV9TgV1cyosR7qdnkc8FTEyM1', {

      at new Spec (node_modules/@jest/core/node_modules/jest-jasmine2/build/jasmine/Spec.js:116:22)
      at Suite.<anonymous> (lambda-view.spec.ts:107:5)

 FAIL  ./local-forging.spec.ts (53.668 s)
  ● Test local forger: https://api.tez.ie/rpc/falphanet › Should give the same result as when forging with the rpc: Transaction with custom entrypoint (https://api.tez.ie/rpc/falphanet)

    expect(received).toEqual(expected) // deep equality

    Expected: "a99b946c97ada0f42c1bdeae0383db7893351232a832d00d0cd716eb6f66e5616c0035e993d8c7aaa42b5e3ccd86a33390ececc73abd904e010a0ae80701609b26857d9053ecda49f13369a3c8908abc30ef00ff0500000018070707070a000000020202008a03010000000568656c6c6f"
    Received: "a99b946c97ada0f42c1bdeae0383db7893351232a832d00d0cd716eb6f66e5616c0035e993d8c7aaa42b5e3ccd86a33390ececc73abd904e010a0ae80701609b26857d9053ecda49f13369a3c8908abc30ef00ffff046d61696e00000018070707070a000000020202008a03010000000568656c6c6f"

      15 |                 const result = await localForger.forge(operation);
      16 |                 const rpcResult = await Tezos.rpc.forgeOperations(operation);
    > 17 |                 expect(result).toEqual(rpcResult);
         |                                ^
      18 |                 expect(await localForger.parse(result)).toEqual(expected || operation);
      19 |                 done();
      20 |             });

      at local-forging.spec.ts:17:32
      at step (local-forging.spec.ts:33:23)
      at Object.next (local-forging.spec.ts:14:53)
      at fulfilled (local-forging.spec.ts:5:58)

 FAIL  ./contract-set-delegate-auto-estimate.spec.ts (6.264 s)
  ● Test account delegation with estimation using: https://api.tez.ie/rpc/falphanet › delegates account to known baker with automatic estimate

    expect(received).toMatch(expected)

    Expected substring: "delegate.unchanged"
    Received string:    "(temporary) proto.009-PsrsRVg1.delegation.unchanged"

      24 |       } catch (ex) {
      25 |         //When running tests more than one time with the same faucet key, the account is already delegated to the given delegate
    > 26 |         expect(ex.message).toMatch('delegate.unchanged')
         |                            ^
      27 |       }
      28 |       done();
      29 |     });

      at contract-set-delegate-auto-estimate.spec.ts:26:28
      at step (contract-set-delegate-auto-estimate.spec.ts:33:23)
      at Object.throw (contract-set-delegate-auto-estimate.spec.ts:14:53)
      at rejected (contract-set-delegate-auto-estimate.spec.ts:6:65)

**Comment by roxaneletourneau** [comment]
Running the integration test `contract-register-selegate.spec.ts` give the following error:
`(temporary) proto.009-PsrsRVg1.operation.not_an_active_consensus_key`
